---
title: "NYC Restaurant Inspections Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    navbar:
      - { title: "Home", href: index.html, align: right }
      - { icon: fa-envelope, href: mailto:yl5219@cumc.columbia.edu, align: right }
      - { icon: fa-github, href: "https://www.linkedin.com/in/yuqing-liu1/", align: right }
      - { icon: fa-linkedin, href: "https://github.com/yuqingliu6", align: right }
    source: embed
    theme: flatly
---

```{r setup, include=FALSE}
library(flexdashboard)
library(p8105.datasets)
library(tidyverse)
library(plotly)
library(lubridate)
```

Row 
-----------------------------------------------------------------------

### Chart A

```{r fig.width=60}
rest_inspec |> 
  janitor::clean_names() |>
  mutate(inspection_date <- as.Date(inspection_date)) |>
  filter(inspection_date >= as.Date("2014-01-01"), 
         score != "Missing", score >= 0, boro != "Missing") |>
  mutate(year = year(inspection_date)) |>
  mutate(grade = case_when(0 <= score & score <= 13 ~ "Grade A",
                         14 <= score & score <= 27 ~ "Grade B",
                         score >= 28 ~ "Grade C")) |>
  group_by(boro,grade, year) |>
  summarise(Count = n()) |>
  rename(Grade = grade) |>
  plot_ly(x = ~boro, y = ~Count, color = ~Grade, 
          frame = ~year, type = "bar", alpha = 1) |> 
  layout(title = 
           "Number of Restaurants in Each Inspection Grade Level by Borough in New York City, 2014-2017",
         xaxis = list(title = "Borough"),
         yaxis = list(title = "Count"),
         font = list(size = 8))

```




### Chart B


```{r,fig.width=60}
rest_inspec |>
  filter(violation_code %in% c("06C", "06D", "06E", "06A", "06F")) |>
  group_by(cuisine_description, violation_code) |>
  summarise(count = n(), .groups = 'drop')|>
  ungroup() |>
    filter(count > 300) |>
  mutate(cuisine_description = fct_reorder(cuisine_description, count)) |> 
  mutate(cuisine_description = recode(cuisine_description,"Latin (Cuban, Dominican, Puerto Rican, South & Central American)" = "Latin" )) |>
  plot_ly(height = 300,
          y = ~count, color = ~cuisine_description, type = "box", colors = "viridis")|>
  layout(
    title = "Box Plot of High-Ranking Sanitation-Related Violation Counts by Cuisine Description in All Records from 2012 to 2017",
    xaxis = list( tickangle = -45),
    yaxis = list(title = "Count"),
    font = list(size = 8)
  )

```


Row 
-----------------------------------------------------------------------
### Chart C
```{r fig.width=60}
rest_inspec |>
  filter(violation_code %in% c("06C", "06D", "06E", "06A","06F")) |>
  group_by(cuisine_description, violation_code) |>
  summarise(count = n()) |>
  ungroup() |>
  filter(count > 500) |>
  mutate(violation_code = recode(violation_code,"06D" = "Food contact surface not properly washed, rinsed and sanitized","06C" = "Food not protected from potential source of contamination", "06F" = "Wiping cloths soiled or not stored in sanitizing solution", "06A" = "Personal cleanliness inadequate", "06E"= "Sanitized equipment or utensil improperly used or stored.")) |>
  mutate(cuisine_description = fct_reorder(cuisine_description, count, .desc = FALSE)) |>
  mutate(cuisine_description = recode(cuisine_description,"Latin (Cuban, Dominican, Puerto Rican, South & Central American)" = "Latin" )) |>
 plot_ly(height = 300, 
   y = ~cuisine_description, x = ~count,
          color = ~violation_code, type = "bar", alpha = 1, orientation = 'h') |>
  layout(title = "Top 12 Cuisine Types with Highest Sanitary Violation Numbers in New York City in All Records from 2012 to 2017",
         xaxis = list(title = "Count"),
         yaxis = list(title = "Cuisine"),
         font = list(size = 8))
  
```

### Chart D

```{r ,fig.width=60}
rest_inspec |>
  filter(violation_code %in% c("06C", "06D", "06E", "06A","06F")) |>
  mutate(Date = format(inspection_date, "%Y-%m")) |>
  group_by(Date, violation_code) |>
  summarise(count = n()) |>
  ungroup() |>
  mutate(violation_code = violation_code |> fct_relevel("06C", "06D", "06E", "06A","06F")) |>
  mutate(violation_code = recode(violation_code, "06D" = "Food contact surface not properly washed, rinsed and sanitized","06C" = "Food not protected from potential source of contamination", "06F" = "Wiping cloths soiled or not stored in sanitizing solution", "06A" = "Personal cleanliness inadequate", "06E"= "Sanitized equipment or utensil improperly used or stored.")) |>
  plot_ly(x = ~Date, y = ~count,
          color = ~violation_code, type = "scatter", 
          mode = "lines", alpha = 1) |>
  layout(title =  "Sanitory Violations over Time in New York's Restaurants, 2012-2017",
         xaxis = list(title = "Date"),
         yaxis = list(title = "Count"),
         font = list(size = 8)
         )
  
```

